from meu_grafo_lista_adj import MeuGrafo

g = MeuGrafo()
g.adiciona_vertice("J")
g.adiciona_vertice("C")
g.adiciona_vertice("E")
g.adiciona_vertice("P")
g.adiciona_vertice("M")
g.adiciona_vertice("T")
g.adiciona_vertice("Z")
g.adiciona_aresta('a1', 'J', 'C')
g.adiciona_aresta('a2', 'C', 'E')
g.adiciona_aresta('a4', 'P', 'C')
g.adiciona_aresta('a6', 'T', 'C')
g.adiciona_aresta('a8', 'M', 'T')
g.adiciona_aresta('a9', 'T', 'Z')

grafo_teste = MeuGrafo()
grafo_teste.adiciona_vertice("A")
grafo_teste.adiciona_vertice("B")
grafo_teste.adiciona_vertice("C")
grafo_teste.adiciona_vertice("D")
grafo_teste.adiciona_vertice("E")
grafo_teste.adiciona_vertice("F")
grafo_teste.adiciona_aresta("a1", "A", "B")
grafo_teste.adiciona_aresta("a2", "A", "D")
grafo_teste.adiciona_aresta("a3", "B", "C")
grafo_teste.adiciona_aresta("a4", "B", "D")
grafo_teste.adiciona_aresta("a5", "D", "C")
grafo_teste.adiciona_aresta("a6", "D", "E")
grafo_teste.adiciona_aresta("a7", "C", "E")
grafo_teste.adiciona_aresta("a8", "E", "F")

g_c = MeuGrafo()
g_c.adiciona_vertice("J")
g_c.adiciona_vertice("C")
g_c.adiciona_vertice("E")
g_c.adiciona_vertice("P")
g_c.adiciona_aresta('a1', 'J', 'C', 1)
g_c.adiciona_aresta('a2', 'J', 'E', 2)
g_c.adiciona_aresta('a3', 'J', 'P', 2)
g_c.adiciona_aresta('a4', 'E', 'C', 1)
g_c.adiciona_aresta('a5', 'P', 'C', 2)
g_c.adiciona_aresta('a6', 'P', 'E', 1)

g2 = MeuGrafo()
g2.adiciona_vertice("A")
g2.adiciona_vertice("B")
g2.adiciona_vertice("C")
g2.adiciona_vertice("D")
g2.adiciona_vertice("E")
g2.adiciona_aresta("a1", "A", "B", 1)
g2.adiciona_aresta("a2", "A", "E", 3)
g2.adiciona_aresta("a3", "A", "D", 3)
g2.adiciona_aresta("a4", "B", "D", 4)
g2.adiciona_aresta("a5", "B", "C", 3)
g2.adiciona_aresta("a6", "D", "C", 2)
g2.adiciona_aresta("a7", "D", "E", 2)

g3 = MeuGrafo()
g3.adiciona_vertice("A")
g3.adiciona_vertice("B")
g3.adiciona_vertice("C")
g3.adiciona_vertice("D")
g3.adiciona_vertice("E")
g3.adiciona_vertice("F")
g3.adiciona_aresta("a1", "A", "B", 1)
g3.adiciona_aresta("a2", "A", "C", 2)
g3.adiciona_aresta("a3", "B", "D", 2)
g3.adiciona_aresta("a4", "D", "C", 1)
g3.adiciona_aresta("a5", "C", "F", 3)
g3.adiciona_aresta("a6", "B", "E", 2)
g3.adiciona_aresta("a7", "E", "F", 1)

dfs = g.dfs("J")
print(g_c.mst_prim())