from meu_grafo_lista_adj import MeuGrafo

g = MeuGrafo()
g.adiciona_vertice("J")
g.adiciona_vertice("C")
g.adiciona_vertice("E")
g.adiciona_vertice("P")
g.adiciona_vertice("M")
g.adiciona_vertice("T")
g.adiciona_vertice("Z")
g.adiciona_aresta('a1', 'J', 'C')
g.adiciona_aresta('a2', 'C', 'E')
g.adiciona_aresta('a3', 'C', 'E')
g.adiciona_aresta('a4', 'P', 'C')
g.adiciona_aresta('a5', 'P', 'C')
g.adiciona_aresta('a6', 'T', 'C')
g.adiciona_aresta('a7', 'M', 'C')
g.adiciona_aresta('a8', 'M', 'T')
g.adiciona_aresta('a9', 'T', 'Z')

grafo_teste = MeuGrafo()
grafo_teste.adiciona_vertice("A")
grafo_teste.adiciona_vertice("B")
grafo_teste.adiciona_vertice("C")
grafo_teste.adiciona_vertice("D")
grafo_teste.adiciona_vertice("E")
grafo_teste.adiciona_vertice("F")
grafo_teste.adiciona_aresta("a1", "A", "B")
grafo_teste.adiciona_aresta("a2", "A", "D")
grafo_teste.adiciona_aresta("a3", "B", "C")
grafo_teste.adiciona_aresta("a4", "B", "D")
grafo_teste.adiciona_aresta("a5", "D", "C")
grafo_teste.adiciona_aresta("a6", "D", "E")
grafo_teste.adiciona_aresta("a7", "C", "E")
grafo_teste.adiciona_aresta("a8", "E", "F")

dfs = g.dfs("J")
print(g.ha_ciclo())
#print(grafo_teste.ha_ciclo())